# Generated by Django 4.2.4 on 2023-09-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_tareas', '0002_tarea_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
