# Generated by Django 4.2.4 on 2023-09-05 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lista_tareas', '0003_prioridad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prioridad',
            options={'verbose_name_plural': 'Prioridades'},
        ),
        migrations.AddField(
            model_name='tarea',
            name='prioridad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lista_tareas.prioridad'),
        ),
    ]
